# Generated by Django 6.0.2 on 2026-02-25 05:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_founder', models.BooleanField(default=True, verbose_name='Is Founder')),
                ('is_investor', models.BooleanField(default=False, verbose_name='Is Investor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StartupEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Company Name')),
                ('legal_structure', models.CharField(blank=True, max_length=100, verbose_name='Legal Structure')),
                ('incorporation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Incorporation Year')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('stage', models.CharField(choices=[('IDEA', 'Idea Stage'), ('MVP', 'MVP Launched'), ('PRE_SEED', 'Pre-Seed'), ('SEED', 'Seed'), ('SERIES_A', 'Series A'), ('GROWTH', 'Growth')], db_index=True, default='IDEA', max_length=20, verbose_name='Current Stage')),
                ('funding_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Funding Raised (USD)')),
                ('total_score', models.IntegerField(db_index=True, default=0, verbose_name='Total Score')),
                ('rating', models.CharField(blank=True, choices=[('HIGH_RISK', 'High Risk'), ('MODERATE', 'Moderate'), ('STRONG', 'Strong'), ('HIGH_POTENTIAL', 'High Potential')], db_index=True, max_length=20, null=True, verbose_name='Rating Classification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Founder')),
            ],
            options={
                'verbose_name': 'Startup Evaluation',
                'verbose_name_plural': 'Startup Evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationStepData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Step Number')),
                ('step_data', models.JSONField(default=dict, verbose_name='Step Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.startupevaluation', verbose_name='Evaluation')),
            ],
            options={
                'verbose_name': 'Evaluation Step Data',
                'verbose_name_plural': 'Evaluation Step Data List',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='startupevaluation',
            index=models.Index(fields=['user', '-created_at'], name='core_startu_user_id_0b3853_idx'),
        ),
        migrations.AddIndex(
            model_name='startupevaluation',
            index=models.Index(fields=['rating', 'total_score'], name='core_startu_rating_f4633e_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationstepdata',
            index=models.Index(fields=['evaluation', 'step_number'], name='core_evalua_evaluat_33d8f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationstepdata',
            unique_together={('evaluation', 'step_number')},
        ),
    ]
