# Generated by Django 6.0.2 on 2026-03-12 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_pipelinestage_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, default='', max_length=255)),
                ('target_industries', models.JSONField(blank=True, default=list, help_text='List of industries of interest')),
                ('preferred_stages', models.JSONField(blank=True, default=list, help_text="e.g., ['Seed', 'Series A']")),
                ('min_ticket_size', models.IntegerField(blank=True, null=True)),
                ('max_ticket_size', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
