# Generated by Django 6.0.2 on 2026-03-12 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_investorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('incorporation_year', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Registry Entry',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('headline', models.TextField()),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('mentions', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='0-100 score')),
                ('popularity_score', models.FloatField(default=0.0, help_text='0-100 score')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Signal',
                'ordering': ['-collected_at'],
            },
        ),
    ]
