# Generated by Django 6.0.2 on 2026-03-12 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companyregistryentry_newsarticle_socialsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedStartup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Structured Startup',
                'db_table': 'startups',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('round_name', models.CharField(blank=True, default='', max_length=100)),
                ('announced_on', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_events', to='core.enrichedstartup')),
            ],
            options={
                'verbose_name': 'Funding Event',
                'db_table': 'funding_events',
                'ordering': ['-announced_on', '-created_at'],
            },
        ),
    ]
