# Generated by Django 6.0.2 on 2026-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enrichedstartup_fundingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupevaluation',
            name='market_momentum',
            field=models.CharField(blank=True, default='Medium', max_length=50, verbose_name='Market Momentum'),
        ),
        migrations.AddField(
            model_name='startupevaluation',
            name='opportunity_score',
            field=models.IntegerField(default=0, verbose_name='Opportunity Score'),
        ),
        migrations.AddField(
            model_name='startupevaluation',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='Risk Score'),
        ),
    ]
