# Generated by Django 6.0.2 on 2026-03-13 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_startupevaluation_market_momentum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupInvestorMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(db_index=True, default=0, verbose_name='Match Score')),
                ('rationale', models.TextField(blank=True, default='', verbose_name='Match Rationale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_matches', to='core.investorprofile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_matches', to='core.startupevaluation')),
            ],
            options={
                'verbose_name': 'Startup-Investor Match',
                'verbose_name_plural': 'Startup-Investor Matches',
                'db_table': 'startup_investor_matches',
                'ordering': ['-match_score'],
                'unique_together': {('startup', 'investor')},
            },
        ),
    ]
