# Generated by Django 6.0.2 on 2026-03-13 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_startupinvestormatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredStartup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Company Name')),
                ('founder_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Founder Name')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Product Name')),
                ('source', models.CharField(choices=[('news', 'News Feed'), ('social', 'Social Signal / LinkedIn'), ('launch', 'Product Launch')], db_index=True, default='news', max_length=20, verbose_name='Discovery Source')),
                ('headline', models.TextField(blank=True, default='', verbose_name='Headline / Announcement')),
                ('article_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='Source URL')),
                ('industry_keywords', models.JSONField(blank=True, default=list, verbose_name='Industry Keywords')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Product Category')),
                ('announcement_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Announcement Type')),
                ('is_converted', models.BooleanField(default=False, help_text='True once this discovery is converted to a StartupEvaluation record.', verbose_name='Converted to Startup Evaluation')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discovered Startup',
                'verbose_name_plural': 'Discovered Startups',
                'db_table': 'discovered_startups',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['source', '-discovered_at'], name='discovered__source_69ce82_idx')],
            },
        ),
    ]
