# Generated by Django 6.0.2 on 2026-03-13 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_discoveredstartup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('news_score', models.IntegerField(default=0)),
                ('sentiment_score', models.IntegerField(default=0)),
                ('industry_momentum', models.IntegerField(default=0)),
                ('market_momentum', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('investor_attention', models.CharField(choices=[('Rising', 'Rising'), ('Stable', 'Stable'), ('Falling', 'Falling')], default='Stable', max_length=20)),
                ('recent_news_activity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_signal', to='core.startupevaluation')),
            ],
            options={
                'verbose_name': 'Startup Signal',
                'verbose_name_plural': 'Startup Signals',
                'db_table': 'startup_signals',
            },
        ),
    ]
